version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - echo env init
  build:
    commands:
      - echo Building the Go code...
      - "chmod +x ./build.sh"
      - "./build.sh"
  post_build:
    commands:
      - aws s3 sync build/ s3://$S3_BUCKET
